Crossplatform changes to build on Windows
#include <numeric> in shape_2d.cpp for std::iota

Fix points-as-tori\src\cpp\shape_3d.cpp(121,17): : 'i': index variable in OpenMP 'for' statement must have signed integral type
This is an odd one, and can be fixed by changing compiler flags (/openmp:llvm), or by using a signed type for the index. Eigen::Matrix.col uses an Eigen::Index so using Eigen::Index directly seems like the best solution.
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3016?view=msvc-170error C3016

The demo requires open3d and the double quotes appear to be a typo
pip install pyglet "imgui[pyglet] pyvista"
-> pip install pyglet imgui[pyglet] pyvista open3d

People often copy-paste commands without reading so adding "cd demo" would be user friendly.
cd demo
python demo_3d.py